In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [21]:
boston_df = pd.read_csv('codeit/boston.csv')
boston_df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [22]:
boston_df.shape

(506, 14)

In [23]:
x = boston_df.drop(columns='MEDV')

In [24]:
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [25]:
x = x[['AGE']]
x

      AGE
0    65.2
1    78.9
2    61.1
3    45.8
4    54.2
..    ...
501  69.1
502  76.7
503  91.0
504  89.3
505  80.8

[506 rows x 1 columns]

In [26]:
y = boston_df[['MEDV']]
y

     MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [27]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state =5)

In [28]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 1)
(102, 1)
(404, 1)
(102, 1)

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
model = LinearRegression()

In [36]:
model.fit(x_train, y_train)

LinearRegression()

In [37]:
model.coef_

array([[-0.12402883]])

In [38]:
model.intercept_

array([31.04617413])

In [39]:
# f(x) = 31.04617413 -0.12402883x

In [41]:
y_test_prediction = model.predict(x_test)
y_test_prediction

array([[20.31768041],
       [28.14389953],
       [22.84786852],
       [18.64329122],
       [24.62148078],
       [19.99520545],
       [19.75955068],
       [22.79825699],
       [20.92542167],
       [21.74401194],
       [23.29437231],
       [25.41526529],
       [21.53316293],
       [25.94858925],
       [23.76568186],
       [24.55946636],
       [18.64329122],
       [18.64329122],
       [22.00447248],
       [18.64329122],
       [18.89134887],
       [18.90375176],
       [21.33471681],
       [22.71143681],
       [28.46637448],
       [19.06498923],
       [24.31140871],
       [22.05408402],
       [26.32067574],
       [26.59353916],
       [19.0153777 ],
       [18.85414022],
       [19.30064401],
       [18.7301114 ],
       [28.76404367],
       [18.92855752],
       [21.5579687 ],
       [19.21382383],
       [19.69753626],
       [29.08651863],
       [19.56110455],
       [18.64329122],
       [21.02464473],
       [20.14404005],
       [24.72070384],
       [25.16720763],
       [18.64329122],
       [19.5238959 ],
       [18.97816905],
       [19.43707572],
       [20.47891789],
       [25.62611429],
       [25.46487682],
       [19.02778059],
       [18.82933446],
       [26.61834493],
       [26.46951033],
       [20.31768041],
       [27.18887754],
       [25.37805664],
       [21.16107645],
       [25.19201339],
       [19.13940653],
       [18.96576617],
       [20.70216978],
       [19.13940653],
       [19.33785266],
       [30.23998674],
       [28.87566962],
       [24.44784042],
       [19.43707572],
       [24.49745195],
       [23.35638672],
       [18.64329122],
       [18.64329122],
       [26.5687334 ],
       [19.31304689],
       [19.27583824],
       [19.32544978],
       [19.22622671],
       [19.79675933],
       [19.39986707],
       [19.72234203],
       [19.26343536],
       [27.18887754],
       [18.85414022],
       [21.93005519],
       [19.0153777 ],
       [23.85250204],
       [28.75164079],
       [24.39822889],
       [19.98280257],
       [20.13163716],
       [18.64329122],
       [28.91287827],
       [28.42916583],
       [18.84173734],
       [26.76717952],
       [24.37342312],
       [19.38746419],
       [23.02150888],
       [24.95635862]])

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
mean_squared_error(y_test, y_test_prediction) ** 0.5

8.236881612652455